### ISSUE TITLE
Bounds undefined error

### ISSUE THREAD

**Issue by Fleisch** [moagrius/isOnScreen#4]
So I'm using a theme that I believe is using an older version of your code and I'm getting the following error

    TypeError: undefined is not an object (evaluating 'bounds.left')

I did a console.log(bounds) and bounds has valid values for left and top. Testing in Chrome and Safari.

```javascript
$.fn.is_on_screen = function(){
     
    var win = $(window);
     
    var viewport = {
        top : win.scrollTop(),
        left : win.scrollLeft()
    };
    viewport.right = viewport.left + win.width();
    viewport.bottom = viewport.top + win.height();
     
    var bounds = this.offset();
    bounds.right = bounds.left + this.outerWidth();
    bounds.bottom = bounds.top + this.outerHeight();
     
    return (!(viewport.right < bounds.left || viewport.left > bounds.right || viewport.bottom < bounds.top || viewport.top > bounds.bottom));
     
};
```

**Comment by moagrius** [comment]
If bounds is defined and has a value for left, I'm not sure what error you're getting.  You can try alternate versions here: http://upshots.org/javascript/jquery-test-if-element-is-in-viewport-visible-on-screen

**Comment by Fleisch** [comment]
So if change the code to:

```javascript
var bounds = this.offset();
console.log(bounds);
bounds.right = bounds.left + this.outerWidth();
bounds.bottom = bounds.top + this.outerHeight();
```

I get this result in console:

![image](https://cloud.githubusercontent.com/assets/1225836/8940824/f3cf475e-3539-11e5-9fff-fef5ddf4a654.png)

**Comment by moagrius** [comment]
yikes - 6 months delay - this apparently got past my notifications - hope you got it resolved - post back if not - closing for now
