### ISSUE TITLE
situation: element larger than viewport

### ISSUE THREAD

**Issue by creative-resort** [moagrius/isOnScreen#6]
Hi,
good work, this plugin!
**Question:**
What if the element is larger (e.g. higher) than the viewport?
In this case we have the element even more than 100% on screen.
How can that be checked and made to result in "true" with this plugin?
Thank you :)

**Comment by moagrius** [comment]
if you just want to test top edge and don't have nested scrollers, you can use a very light version:

```
$.fn.isOnScreen = function(){
    var element = this.get(0);
    var bounds = element.getBoundingClientRect();
    return bounds.top < window.innerHeight;
}
```

see http://upshots.org/javascript/jquery-test-if-element-is-in-viewport-visible-on-screen
